"""empty message

Revision ID: 9946c4082d1d
Revises: 
Create Date: 2022-10-27 11:29:03.685880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9946c4082d1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breakfast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('prep_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breakfast')
    # ### end Alembic commands ###
